In [ ]:
#1
def linearSearch(array,n,x):
    for i in range(0,n):
        if(array[i] == x):
            return i
        return -1
array=[2,3,4,5,6]
x=eval(input("enter the number to be searched: "))
n=len(array)
result=linearSearch(array,n,x)
if(result==-1):
    print("Element not found")
else:
    print("element found at index :",result)
            
    

In [31]:
import numpy as np
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
print("printing array")
print(a)
print("printing numpy array attributes")
print("1) array dimension:",a.ndim)
print("2) array shape:",a.shape)
print("3)array size:",a.size)
print("4) array data type:",a.dtype)
print("5) the length of each array item in bytes is:",a.itemsize)

printing array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
printing numpy array attributes
1) array dimension: 2
2) array shape: (3, 3)
3)array size: 9
4) array data type: int32
5) the length of each array item in bytes is: 4


In [29]:
#2
import bisect
def insert(list,n):
    bisect.insort(list,n)
    return list
list=[1,2,4]
n=eval(input("enter the value to be inserted"))
print(insert(list,n))

enter the value to be inserted1
[1, 1, 2, 4]


In [23]:
import bisect
def insert(list,n):
    bisect.insort(list,n)
    return list
list=[1,2,3,4]
n=eval(input("enter the value to be inserted: "))
print(insert(list,n))

enter the value to be inserted: 11
[1, 2, 3, 4, 11]


In [36]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("printing attribute")
print(a)
print("printing numpy array attribute")
print("1)array dimension",a.ndim)
print("2)array size",a.size)
print("3)array shape",a.shape)
print("4)array data type",a.dtype)
#print("5)iteam in bytes",a.itemsize)

printing attribute
[[1 2 3]
 [4 5 6]
 [7 8 9]]
printing numpy array attribute
1)array dimension 2
2)array size 9
3)array shape (3, 3)
4)array data type int32
